name: config_map
description: "Helper class for converting string values of  object in predefined types and for editing ones"
version: 0.1.1
homepage: https://github.com/adkrix/config_map
repository: https://github.com/adkrix/config_map

environment:
  sdk: ^3.9.0

dependencies:
  collection: ^1.19.1

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6

platforms:
  android:
  ios:
  linux:
  macos:
  windows:
  web:

topics:
  - map
  - object
  - data
  - converting
